apiVersion: v1
kind: Secret
metadata:
  name: iccsys-prod-secret
type: Opaque
data:
  SESSION_SECRET: <path:kv/data/iccsys-prod#SESSION_SECRET | base64encode>
  PORT: <path:kv/data/iccsys-prod#PORT | base64encode>
  DB_HOST: <path:kv/data/iccsys-prod#DB_HOST | base64encode>
  DB_USERNAME: <path:kv/data/iccsys-prod#DB_USERNAME | base64encode>
  DB_NAME: <path:kv/data/iccsys-prod#DB_NAME | base64encode>
  DB_DIALECT: <path:kv/data/iccsys-prod#DB_DIALECT | base64encode>
  DB_LOGGING: <path:kv/data/iccsys-prod#DB_LOGGING | base64encode>
  DB_TIMEZONE: <path:kv/data/iccsys-prod#DB_TIMEZONE | base64encode>
  ICC_UPLOAD_PATH: <path:kv/data/iccsys-prod#ICC_UPLOAD_PATH | base64encode>
  ICCSYS_UPLOAD_PATH: <path:kv/data/iccsys-prod#ICCSYS_UPLOAD_PATH | base64encode>
  MINIO_ENDPOINT: <path:kv/data/iccsys-prod#MINIO_ENDPOINT | base64encode>
  MINIO_PORT: <path:kv/data/iccsys-prod#MINIO_PORT | base64encode>
  MINIO_OBJECT_PREFIX: <path:kv/data/iccsys-prod#MINIO_OBJECT_PREFIX | base64encode>
  MINIO_BUCKET_NAME: <path:kv/data/iccsys-prod#MINIO_BUCKET_NAME | base64encode>
  MINIO_ACCESS_KEY: <path:kv/data/iccsys-prod#MINIO_ACCESS_KEY | base64encode>
  MINIO_SECRET_KEY: <path:kv/data/iccsys-prod#MINIO_SECRET_KEY | base64encode>
  MINIO_USE_SSL: <path:kv/data/iccsys-prod#MINIO_USE_SSL | base64encode>
  PERMIT_STUDENT_COUNT: <path:kv/data/iccsys-prod#PERMIT_STUDENT_COUNT | base64encode>
  PERMIT_STUDENT_COUNT_SEMICON: <path:kv/data/iccsys-prod#PERMIT_STUDENT_COUNT_SEMICON | base64encode>
