apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iccsys-qa
nameSuffix: -qa
resources:
- ../../base
- namespace.yaml
- secret.yaml
- ingress.yaml
images:
- name: scgskku/iccsys
  newName: scgskku/iccsys-qa
  newTag: d20ebac5fabb2d0611ffe44141cfff078d8147b6-36652702878-1
