apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iccsys-qa
nameSuffix: -qa
resources:
- ../../base
- namespace.yaml
- secret.yaml
- ingress.yaml
images:
- name: scgskku/iccsys
  newName: scgskku/iccsys-qa
  newTag: f38161c02a801c574094c3bb2625b39d7e4ba33d-36654617685-1
