apiVersion: v1
kind: Secret
metadata:
  name: iccsys-secret
type: Opaque
data:
  SESSION_SECRET: <path:kv/data/iccsys-qa#session-secret | base64encode>
  QA_SERVER_PORT: <path:kv/data/iccsys-qa#port | base64encode>
  QA_DB_HOST: <path:kv/data/iccsys-qa#db-host | base64encode>
  QA_DB_DATABASE: <path:kv/data/iccsys-qa#db-name | base64encode>
  QA_DB_USERNAME: <path:kv/data/iccsys-qa#db-username | base64encode>
  QA_DB_PASSWORD: <path:kv/data/iccsys-qa#db-password | base64encode>
  QA_DB_DIALECT: <path:kv/data/iccsys-qa#db-dialect | base64encode>
  QA_DB_LOGGING: <path:kv/data/iccsys-qa#db-logging | base64encode>
  QA_DB_TIMEZONE: <path:kv/data/iccsys-qa#db-timezone | base64encode>
  QA_ICC_UPLOAD_PATH: <path:kv/data/iccsys-qa#icc-upload-path | base64encode>
  QA_ICCSYS_UPLOAD_PATH: <path:kv/data/iccsys-qa#iccsys-upload-path | base64encode>
  MINIO_ENDPOINT: <path:kv/data/iccsys-qa#minio-endpoint | base64encode>
  MINIO_PORT: <path:kv/data/iccsys-qa#minio-port | base64encode>
  MINIO_OBJECT_PREFIX: <path:kv/data/iccsys-qa#minio-object-prefix | base64encode>
  MINIO_BUCKET_NAME: <path:kv/data/iccsys-qa#minio-bucket-name | base64encode>
  MINIO_ACCESS_KEY: <path:kv/data/iccsys-qa#minio-access-key | base64encode>
  MINIO_SECRET_KEY: <path:kv/data/iccsys-qa#minio-secret-key | base64encode>
  MINIO_USE_SSL: <path:kv/data/iccsys-qa#minio-use-ssl | base64encode>
  PERMIT_STUDENT_COUNT: <path:kv/data/iccsys-qa#permit-student-count | base64encode>
  PERMIT_STUDENT_COUNT_SEMICON: <path:kv/data/iccsys-qa#permit-student-count-semicon | base64encode>
  UPLOAD_BASE_PATH: <path:kv/data/iccsys-qa#upload-base-path | base64encode>
